### ISSUE TITLE
Cakephp 3.07 fatal error

### ISSUE THREAD

**Issue by bahamastudio** [cake17/cakephp-recaptcha#10]
Hi,
Thank's for a great plugin. After upgrading my app to Cakephp 3.07 i have following error. **Fatal error: Access level to Recaptcha\Controller\Component\RecaptchaComponent::$response must be public (as in class Cake\Controller\Component) in ...\vendor\cake17\cakephp-recaptcha\src\Controller\Component\RecaptchaComponent.php on line 102**

**Comment by cake17** [comment]
Hi,
Thanks for reporting this issue !

I fixed it in the last commit, you can update the plugin with `composer update`.
Please don't hesitate to tell me if you see other issues.

**Comment by bahamastudio** [comment]
Thank you for your quick response.
Now I receive: **Error: Call to undefined method Recaptcha\Recaptcha\RecaptchaResponse::body() 
File ..\vendor\cakephp\cakephp\src\Controller\Controller.php 
Line: 582**

**Comment by cake17** [comment]
Ok this should be better !?

**Comment by bahamastudio** [comment]
Yes. It's working. Thank you very much.
Have a nice day.

**Comment by cake17** [comment]
you too !
