### ISSUE TITLE
Config error

### ISSUE THREAD

**Issue by ghost** [cake17/cakephp-recaptcha#11]
I followed the instructions and keep getting a config error.

You must set the secret Recaptcha key in config/recaptcha.php file

The only way to get it to work is to put the below in my bootstrap.php
Configure::load('recaptcha', 'default', false);

The method in your bootstrap.php is not loading the config.

Configure::config('default', new PhpConfig(dirname(APP) . DS . 'config' . DS));
Configure::load('recaptcha', 'default', false);

What could be wrong?

**Comment by cake17** [comment]
Thanks for reporting your issue, I'll have a look at this tomorrow.
I'm thinking about changing the way recaptcha config is loaded and maybe use environnement variables.

**Comment by ghost** [comment]
Thanks for your time. I will continue to look also.

**Comment by cake17** [comment]
It seems to work on my station. Just small questions:
- where did you copy the `recaptcha.php` ?
- did you add this in yout bootstrap : `Plugin::load('Recaptcha', ['routes' => true, 'bootstrap' => true]);` ?

**Comment by ghost** [comment]
Yes I added the plugin:load to bootstrap and put the recaptcha.php into /config for the app not the plugin.

**Comment by cake17** [comment]
Mystery... I rechecked with a fresh install of CakePHP and it's working, that's wired.

The only things I can think of are :
- try with a fresh install of cakephp
- ensure you have the 'bootstrap' => true when loading the plugin
- I changed the `sitekey` name (it was siteKey before) : I can see my readme is not up-to-date

Let me know

**Comment by ghost** [comment]
I am using this config

```
return [
    'Recaptcha' => [
        // Register API keys at https://www.google.com/recaptcha/admin
        'sitekey' => 'my-info',
        'secret' => 'my-info',
        // reCAPTCHA supported 40+ languages listed
        // here: https://developers.google.com/recaptcha/docs/language
        'lang' => 'en',
        // either light or dark
        'theme' => 'light',
        // either image or audio
        'type' => 'image',
    ]
];

Plugin::loadAll([
        'Migrations',
        'Search',
        'TinyAuth' => array('bootstrap' => true),
        'Recaptcha', ['routes' => true, 'bootstrap' => true]
        ]);


php version 5.6.10
```

**Comment by ghost** [comment]
I am getting the error 'secret' not set.

**Comment by ghost** [comment]
I went through the whole install again and when I go the the register page I get the below.

![screen shot 2015-08-21 at 7 16 52 am](https://cloud.githubusercontent.com/assets/5669247/9407164/c4330122-47d4-11e5-86d8-1aad4b27f260.png)

**Comment by cake17** [comment]
can you try this:
- install a new version of cakephp (composer create-project --prefer-dist cakephp/app test_recaptcha)
- add the plugin in composer, follow the readme instructions
- go to http:your-url/recaptcha/contact

Just to check, maybe there is a confllict with another plugin

**Comment by ghost** [comment]
Will do later today and get back with you.

**Comment by ghost** [comment]
I am new at this so please bare with me, I wan to use this for a register page. I currently have a table setup and validation in the model and a form in the view. How do I use my existing resources. I see your contactform.php has it's own.

**Comment by cake17** [comment]
so you tried it and this worked for the contact recaptcha provided by the plugin ?

**Comment by cake17** [comment]
Just adapt the 5, 6 and 7 of the readme for your controller and view. We'll find the solution :smile:

**Comment by ghost** [comment]
Worked on it some more, the blackhole issue was due to having the following.

```
$this->loadComponent('Security');
```

It functions fine now but I still have to load the config myself in bootstrap to read the values.

```
Configure::load('recaptcha', 'default');
```

**Comment by ghost** [comment]
After verifying security was causing the blackhole issue I set it back on for the App and put the below in the beforefilter to disable it just for registrations.

```
$this->Security->config('unlockedActions', ['register']);
```
