### ISSUE TITLE
The 'data-size' attribute is not supported

### ISSUE THREAD

**Issue by chnvcode** [cake17/cakephp-recaptcha#12]
The 'size' parameter should be configurable to change the size of the widget.

**Comment by cake17** [comment]
@chnvcode You're right, I will add the size parameter, unless you want to give it a try ?
This repo is depreciated, so I'll make the changes [here](https://github.com/cakephp-fr/recaptcha).

I created your issue in the [other repo](https://github.com/cakephp-fr/recaptcha/issues/1)
