### ISSUE TITLE
Flash Messages not printing

### ISSUE THREAD

**Issue by javikalsan** [cake17/cakephp-recaptcha#5]
The Flash messages function in the Component:
$controller->Flash->error(__d('recaptcha', 'Please check Recaptcha Box.'), ['key' => 'error']);
is not printing anything but is in $_SESSION:
![session](https://cloud.githubusercontent.com/assets/1070397/6168237/b6f6aaa0-b2c3-11e4-8566-7f9b30273344.png)
The layout is ussing correctly: <?= $this->Flash->render() ?>

**Comment by cake17** [comment]
If you print `<?= $this->Flash->render('error') ?>`, I think it should print the error message.

By default, it goes into `<?= $this->Flash->render() ?>`, but when using `$controller->Flash->error()`, it is render with Flash->render('error').

Let me know if it works :)

**Comment by javikalsan** [comment]
Don't work, same result, i'm testing it with cakephp 3 default layout

**Comment by cake17** [comment]
That's why, you need to change the default layout.

It should work if you add `<?= $this->Flash->render('error') ?>` in your layout just under `<?= $this->Flash->render() ?>` ?

I'll make a PR to add it it natively to default layout, but for now it should work ?

**Comment by cake17** [comment]
I made a proposal here https://github.com/cakephp/app/pull/222

**Comment by ADmad** [comment]
> but when using $controller->Flash->error(), it is render with Flash->render('error').

No it's not. `$controller->Flash->error()` sets the `element` to `error` not the key.

**Comment by ADmad** [comment]
@javikalsan You specify `'key' => 'error'` but in session the key used id `alert/error`. Cake doesn't do that. You have something else which modifies the key.

Either way if you specify custom key you have to use that key as param in helper call `$this->Flash->render('error');`

**Comment by cake17** [comment]
Thanks @ADmad, the key and element were confusing to me. Now it's clearer so I'm gonna remove the `key => error` in Flash messages so that everything can be rendered with `$this->Flash->render()`

**Comment by javikalsan** [comment]
@ADmad understood @cake17 now working ok with $this->Flash->render()

Cheers
