### ISSUE TITLE
Form data not posting.

### ISSUE THREAD

**Issue by karljakober** [cake17/cakephp-recaptcha#6]
I have a very simple contact controller set up

ContactController.php

```
    public function initialize()
    {
        parent::initialize();
        $this->loadComponent('Recaptcha.Recaptcha');
    }

    public function index()
    {
        if ($this->request->is('post')) {
            pr($this->request->data);
            exit();
        }
    }
```

index.ctp

```
<?= $this->Form->create() ?>
<?= $this->Form->input('test') ?>
<?= $this->Recaptcha->display() ?>
<?= $this->Form->button('Submit', [
    'type' => 'submit',
]) ?>
<?= $this->Form->end() ?>
```

When the form is submitted, the data array is not printed on screen, if i comment out both the load component and the recaptcha display in the view, the form works fine.

**Comment by cake17** [comment]
The recaptcha checkbox has been checked ? If not, the user is redirected to the same page without post data.

But maybe I can change it to still pass the post data. I'll have a look at it, thanks for your feedback :-)

**Comment by karljakober** [comment]
yes, the checkbox has been checked, if it is not checked a flash error is presented properly (would be nice to still redirect the $this->request->data as to repopulate the form though)

**Comment by karljakober** [comment]
Maybe it has something to do with the security component?

**Comment by cake17** [comment]
@KarlJakober Sorry for the delay. Let me know if the request data are still missing, it should work now.

**Comment by cake17** [comment]
I close this, it's normally fixed. @KarlJakober please reopen this if not
