### ISSUE TITLE
Fatal error: Using method return value in write context

### ISSUE THREAD

**Issue by PhantomWatson** [cake17/cakephp-recaptcha#8]
Using this plugin, I'm getting the following error:

```
Fatal error: Can't use method return value in write context in C:\cakephp\vendor\cake17\cakephp-recaptcha\src\View\Helper\RecaptchaHelper.php on line 64
```

That line is 

```
if (empty($this->config('lang'))) {
```

and the error is corrected if that's changed to

```
$lang = $this->config('lang');
if (empty($lang)) {
```

This is due to a [limitation of using `empty()` in versions of PHP before 5.5](http://stackoverflow.com/a/1075559/52530).

**Comment by cake17** [comment]
Thanks @PhantomWatson, this is fixed, let me know if something else is wrong !

**Comment by PhantomWatson** [comment]
No problem! Sorry I didn't have the time to whip up a fork and a pull request.

Thanks so much for your work on this plugin!
