### ISSUE TITLE
Comment tester la fonction register avec le plugin.

### ISSUE THREAD

**Issue by Xety** [cake17/cakephp-recaptcha#9]
Bonjour,

Déjà merci pour le plugin, il fonctionne parfaitement.
Par contre, j'ai un problème avec mes tests unitaires. J'ai des tests pour ma fonction login (register), mais je n'arrive pas à les adapter pour les refaire fonctionner avec la captcha : https://github.com/Xety/Xeta/blob/master/tests/TestCase/Controller/UsersControllerTest.php#L107-L120

En faite, il faudrait que j'arrive à simuler la fonction `$this->Recaptcha->verify()` qui est dans la fonction `login()`, mais vue que je suis pas un pro avec PHPUnit, j'ai un peut de mal, aurais-tu une idée de comment faire ?

**Comment by cake17** [comment]
Bonjour,

Désolé pour la réponse un peu tardive... Je suis pas très fort non plus avec PHPUnit (pas beaucoup de tests dans le plugin d'ailleurs).
Je laisse ton issue ouverte si jamais quelqu'un de passage a une solution à ton problème.

**Comment by Xety** [comment]
Après 6 mois, je reviens aux nouvelles. (Enfin, je suis passé par hasard sur ton répo, du coup j'en profite pour clore l'issue ^^)
J'ai trouvé un moyen pour bypass le check dans mes controllers en définissant une option `'bypass' => false` dans Recaptcha, puis je test cette option dans mes actions.
Et dans mes tests, je fait un coup de `Configure::write('Recaptcha.bypass', true)` avant une requête et le tour est joué.

Attention à bien mettre l'option à `false` par défaut... :stuck_out_tongue: 

C'est le seul est unique moyen pour le moment, car la reCaptcha de Google ne propose (pas encore?) de feature pour ceci, donc elle est clairement non-bypassable.

**Comment by cake17** [comment]
@Xety Merci pour le retour !

En passant, j'ai déplacé ce repo vers [cakephp-fr](https://github.com/cakephp-fr/recaptcha) pour que plus de personnes puissent le modifier. Je pense le supprimer à moyen terme...

Je t'ai proposé de rejoindre le groupe cakephp-fr/plugins si tu as envie de modifier directement le plugin ou de créer des branches directement sur le repo.

**Comment by Xety** [comment]
Oui, j'ai vue ça.
Peut être informer les gens à propos de ça en modifiant la description dans le `composer.json` et en faisant une nouvelle release ?
Comme ça, avec la cmd `composer show` On verra directement que le plugin est `[DEPRECIATED]`.

Merci pour l'invitation, c'est avec plaisir !
Je vais voir se que je peut apporter comme amélioration dessus.

**Comment by cake17** [comment]
@Xety Bonnes idées, j'ai fait une modif du `composer.json` et une dernière release a été faite. Cool que tu participes à ce plugin :smile:  !
